// This file is automatically generated. Do not edit it directly.
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// Fallback values for development (Lasy preview)
const FALLBACK_SUPABASE_URL = "https://vvgqqlrujmyxzzygsizc.supabase.co";
const FALLBACK_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Z3FxbHJ1am15eHp6eWdzaXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDk1MDYsImV4cCI6MjA3MDU4NTUwNn0.RDBnrokuwaXoQri56NpCUU1HU_VYb6gXxm_AcWniwfo";

// Environment variables (for production deployment)
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || FALLBACK_SUPABASE_ANON_KEY;

// Lazy-loaded Supabase client
let supabaseClient: SupabaseClient | null = null;

function getSupabase(): SupabaseClient {
  if (!supabaseClient) {
    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      throw new Error(
        'Missing Supabase environment variables. Please check your .env.local file.'
      );
    }

    if (typeof window === 'undefined') {
      supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: {
          autoRefreshToken: true,
          persistSession: false,
          detectSessionInUrl: false,
          flowType: 'pkce',
        },
      });
    } else {
      supabaseClient = createClientComponentClient({
        supabaseUrl: SUPABASE_URL,
        supabaseKey: SUPABASE_ANON_KEY,
        options: {
          auth: {
            autoRefreshToken: true,
            detectSessionInUrl: true,
            flowType: 'pkce',
          },
        },
      });
    }
  }
  
  return supabaseClient;
}

// Export both the function and a direct instance for convenience
export const supabase = getSupabase();
export { getSupabase };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// or
// import { getSupabase } from "@/integrations/supabase/client";
// const supabase = getSupabase();
